// Code generated by MockGen. DO NOT EDIT.
// Source: file_config.go

// Package orlop_test is a generated GoMock package.
package orlop_test

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockHasFile is a mock of HasFile interface
type MockHasFile struct {
	ctrl     *gomock.Controller
	recorder *MockHasFileMockRecorder
}

// MockHasFileMockRecorder is the mock recorder for MockHasFile
type MockHasFileMockRecorder struct {
	mock *MockHasFile
}

// NewMockHasFile creates a new mock instance
func NewMockHasFile(ctrl *gomock.Controller) *MockHasFile {
	mock := &MockHasFile{ctrl: ctrl}
	mock.recorder = &MockHasFileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockHasFile) EXPECT() *MockHasFileMockRecorder {
	return m.recorder
}

// GetFile mocks base method
func (m *MockHasFile) GetFile() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetFile indicates an expected call of GetFile
func (mr *MockHasFileMockRecorder) GetFile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockHasFile)(nil).GetFile))
}
