// Code generated by mockery v2.14.0. DO NOT EDIT.

package config

import mock "github.com/stretchr/testify/mock"

// File is an autogenerated mock type for the File type
type File struct {
	mock.Mock
}

type File_Expecter struct {
	mock *mock.Mock
}

func (_m *File) EXPECT() *File_Expecter {
	return &File_Expecter{mock: &_m.Mock}
}

// GetFile provides a mock function with given fields:
func (_m *File) GetFile() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// File_GetFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFile'
type File_GetFile_Call struct {
	*mock.Call
}

// GetFile is a helper method to define mock.On call
func (_e *File_Expecter) GetFile() *File_GetFile_Call {
	return &File_GetFile_Call{Call: _e.mock.On("GetFile")}
}

func (_c *File_GetFile_Call) Run(run func()) *File_GetFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *File_GetFile_Call) Return(_a0 string) *File_GetFile_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewFile interface {
	mock.TestingT
	Cleanup(func())
}

// NewFile creates a new instance of File. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFile(t mockConstructorTestingTNewFile) *File {
	mock := &File{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
