// Code generated by mockery v2.14.0. DO NOT EDIT.

package internal

import mock "github.com/stretchr/testify/mock"

// Parameter is an autogenerated mock type for the Parameter type
type Parameter struct {
	mock.Mock
}

type Parameter_Expecter struct {
	mock *mock.Mock
}

func (_m *Parameter) EXPECT() *Parameter_Expecter {
	return &Parameter_Expecter{mock: &_m.Mock}
}

// Error provides a mock function with given fields:
func (_m *Parameter) Error() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Parameter_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type Parameter_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *Parameter_Expecter) Error() *Parameter_Error_Call {
	return &Parameter_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *Parameter_Error_Call) Run(run func()) *Parameter_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Parameter_Error_Call) Return(_a0 string) *Parameter_Error_Call {
	_c.Call.Return(_a0)
	return _c
}

// Parameter provides a mock function with given fields:
func (_m *Parameter) Parameter() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Parameter_Parameter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parameter'
type Parameter_Parameter_Call struct {
	*mock.Call
}

// Parameter is a helper method to define mock.On call
func (_e *Parameter_Expecter) Parameter() *Parameter_Parameter_Call {
	return &Parameter_Parameter_Call{Call: _e.mock.On("Parameter")}
}

func (_c *Parameter_Parameter_Call) Run(run func()) *Parameter_Parameter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Parameter_Parameter_Call) Return(_a0 string) *Parameter_Parameter_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewParameter interface {
	mock.TestingT
	Cleanup(func())
}

// NewParameter creates a new instance of Parameter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewParameter(t mockConstructorTestingTNewParameter) *Parameter {
	mock := &Parameter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
