// Code generated by mockery v2.14.0. DO NOT EDIT.

package internal

import mock "github.com/stretchr/testify/mock"

// StatusCode is an autogenerated mock type for the StatusCode type
type StatusCode struct {
	mock.Mock
}

type StatusCode_Expecter struct {
	mock *mock.Mock
}

func (_m *StatusCode) EXPECT() *StatusCode_Expecter {
	return &StatusCode_Expecter{mock: &_m.Mock}
}

// Error provides a mock function with given fields:
func (_m *StatusCode) Error() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// StatusCode_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type StatusCode_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *StatusCode_Expecter) Error() *StatusCode_Error_Call {
	return &StatusCode_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *StatusCode_Error_Call) Run(run func()) *StatusCode_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StatusCode_Error_Call) Return(_a0 string) *StatusCode_Error_Call {
	_c.Call.Return(_a0)
	return _c
}

// StatusCode provides a mock function with given fields:
func (_m *StatusCode) StatusCode() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// StatusCode_StatusCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatusCode'
type StatusCode_StatusCode_Call struct {
	*mock.Call
}

// StatusCode is a helper method to define mock.On call
func (_e *StatusCode_Expecter) StatusCode() *StatusCode_StatusCode_Call {
	return &StatusCode_StatusCode_Call{Call: _e.mock.On("StatusCode")}
}

func (_c *StatusCode_StatusCode_Call) Run(run func()) *StatusCode_StatusCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StatusCode_StatusCode_Call) Return(_a0 int) *StatusCode_StatusCode_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewStatusCode interface {
	mock.TestingT
	Cleanup(func())
}

// NewStatusCode creates a new instance of StatusCode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStatusCode(t mockConstructorTestingTNewStatusCode) *StatusCode {
	mock := &StatusCode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
