// Code generated by mockery v2.14.0. DO NOT EDIT.

package env

import mock "github.com/stretchr/testify/mock"

// Environ is an autogenerated mock type for the Environ type
type Environ struct {
	mock.Mock
}

type Environ_Expecter struct {
	mock *mock.Mock
}

func (_m *Environ) EXPECT() *Environ_Expecter {
	return &Environ_Expecter{mock: &_m.Mock}
}

// Getenv provides a mock function with given fields: key
func (_m *Environ) Getenv(key string) string {
	ret := _m.Called(key)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Environ_Getenv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Getenv'
type Environ_Getenv_Call struct {
	*mock.Call
}

// Getenv is a helper method to define mock.On call
//   - key string
func (_e *Environ_Expecter) Getenv(key interface{}) *Environ_Getenv_Call {
	return &Environ_Getenv_Call{Call: _e.mock.On("Getenv", key)}
}

func (_c *Environ_Getenv_Call) Run(run func(key string)) *Environ_Getenv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Environ_Getenv_Call) Return(_a0 string) *Environ_Getenv_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewEnviron interface {
	mock.TestingT
	Cleanup(func())
}

// NewEnviron creates a new instance of Environ. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEnviron(t mockConstructorTestingTNewEnviron) *Environ {
	mock := &Environ{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
