// Code generated by mockery v2.14.0. DO NOT EDIT.

package orlop

import mock "github.com/stretchr/testify/mock"

// HasEnabled is an autogenerated mock type for the HasEnabled type
type HasEnabled struct {
	mock.Mock
}

type HasEnabled_Expecter struct {
	mock *mock.Mock
}

func (_m *HasEnabled) EXPECT() *HasEnabled_Expecter {
	return &HasEnabled_Expecter{mock: &_m.Mock}
}

// GetEnabled provides a mock function with given fields:
func (_m *HasEnabled) GetEnabled() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// HasEnabled_GetEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEnabled'
type HasEnabled_GetEnabled_Call struct {
	*mock.Call
}

// GetEnabled is a helper method to define mock.On call
func (_e *HasEnabled_Expecter) GetEnabled() *HasEnabled_GetEnabled_Call {
	return &HasEnabled_GetEnabled_Call{Call: _e.mock.On("GetEnabled")}
}

func (_c *HasEnabled_GetEnabled_Call) Run(run func()) *HasEnabled_GetEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HasEnabled_GetEnabled_Call) Return(_a0 bool) *HasEnabled_GetEnabled_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewHasEnabled interface {
	mock.TestingT
	Cleanup(func())
}

// NewHasEnabled creates a new instance of HasEnabled. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHasEnabled(t mockConstructorTestingTNewHasEnabled) *HasEnabled {
	mock := &HasEnabled{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
