// Code generated by mockery v2.14.0. DO NOT EDIT.

package parameter

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ObjectStore is an autogenerated mock type for the ObjectStore type
type ObjectStore struct {
	mock.Mock
}

type ObjectStore_Expecter struct {
	mock *mock.Mock
}

func (_m *ObjectStore) EXPECT() *ObjectStore_Expecter {
	return &ObjectStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, p
func (_m *ObjectStore) Delete(ctx context.Context, p string) error {
	ret := _m.Called(ctx, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ObjectStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ObjectStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//  - ctx context.Context
//  - p string
func (_e *ObjectStore_Expecter) Delete(ctx interface{}, p interface{}) *ObjectStore_Delete_Call {
	return &ObjectStore_Delete_Call{Call: _e.mock.On("Delete", ctx, p)}
}

func (_c *ObjectStore_Delete_Call) Run(run func(ctx context.Context, p string)) *ObjectStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ObjectStore_Delete_Call) Return(_a0 error) *ObjectStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

// List provides a mock function with given fields: ctx, p
func (_m *ObjectStore) List(ctx context.Context, p string) ([]string, error) {
	ret := _m.Called(ctx, p)

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ObjectStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ObjectStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//  - ctx context.Context
//  - p string
func (_e *ObjectStore_Expecter) List(ctx interface{}, p interface{}) *ObjectStore_List_Call {
	return &ObjectStore_List_Call{Call: _e.mock.On("List", ctx, p)}
}

func (_c *ObjectStore_List_Call) Run(run func(ctx context.Context, p string)) *ObjectStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ObjectStore_List_Call) Return(_a0 []string, _a1 error) *ObjectStore_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Read provides a mock function with given fields: ctx, p
func (_m *ObjectStore) Read(ctx context.Context, p string) (map[string]interface{}, error) {
	ret := _m.Called(ctx, p)

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]interface{}); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ObjectStore_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type ObjectStore_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//  - ctx context.Context
//  - p string
func (_e *ObjectStore_Expecter) Read(ctx interface{}, p interface{}) *ObjectStore_Read_Call {
	return &ObjectStore_Read_Call{Call: _e.mock.On("Read", ctx, p)}
}

func (_c *ObjectStore_Read_Call) Run(run func(ctx context.Context, p string)) *ObjectStore_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ObjectStore_Read_Call) Return(_a0 map[string]interface{}, _a1 error) *ObjectStore_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// ReadObject provides a mock function with given fields: ctx, p, out
func (_m *ObjectStore) ReadObject(ctx context.Context, p string, out interface{}) error {
	ret := _m.Called(ctx, p, out)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, p, out)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ObjectStore_ReadObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadObject'
type ObjectStore_ReadObject_Call struct {
	*mock.Call
}

// ReadObject is a helper method to define mock.On call
//  - ctx context.Context
//  - p string
//  - out interface{}
func (_e *ObjectStore_Expecter) ReadObject(ctx interface{}, p interface{}, out interface{}) *ObjectStore_ReadObject_Call {
	return &ObjectStore_ReadObject_Call{Call: _e.mock.On("ReadObject", ctx, p, out)}
}

func (_c *ObjectStore_ReadObject_Call) Run(run func(ctx context.Context, p string, out interface{})) *ObjectStore_ReadObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *ObjectStore_ReadObject_Call) Return(_a0 error) *ObjectStore_ReadObject_Call {
	_c.Call.Return(_a0)
	return _c
}

// Write provides a mock function with given fields: ctx, p, data
func (_m *ObjectStore) Write(ctx context.Context, p string, data map[string]interface{}) (map[string]interface{}, error) {
	ret := _m.Called(ctx, p, data)

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) map[string]interface{}); ok {
		r0 = rf(ctx, p, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]interface{}) error); ok {
		r1 = rf(ctx, p, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ObjectStore_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type ObjectStore_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//  - ctx context.Context
//  - p string
//  - data map[string]interface{}
func (_e *ObjectStore_Expecter) Write(ctx interface{}, p interface{}, data interface{}) *ObjectStore_Write_Call {
	return &ObjectStore_Write_Call{Call: _e.mock.On("Write", ctx, p, data)}
}

func (_c *ObjectStore_Write_Call) Run(run func(ctx context.Context, p string, data map[string]interface{})) *ObjectStore_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *ObjectStore_Write_Call) Return(_a0 map[string]interface{}, _a1 error) *ObjectStore_Write_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// WriteObject provides a mock function with given fields: ctx, p, in
func (_m *ObjectStore) WriteObject(ctx context.Context, p string, in interface{}) error {
	ret := _m.Called(ctx, p, in)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, p, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ObjectStore_WriteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteObject'
type ObjectStore_WriteObject_Call struct {
	*mock.Call
}

// WriteObject is a helper method to define mock.On call
//  - ctx context.Context
//  - p string
//  - in interface{}
func (_e *ObjectStore_Expecter) WriteObject(ctx interface{}, p interface{}, in interface{}) *ObjectStore_WriteObject_Call {
	return &ObjectStore_WriteObject_Call{Call: _e.mock.On("WriteObject", ctx, p, in)}
}

func (_c *ObjectStore_WriteObject_Call) Run(run func(ctx context.Context, p string, in interface{})) *ObjectStore_WriteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *ObjectStore_WriteObject_Call) Return(_a0 error) *ObjectStore_WriteObject_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewObjectStore interface {
	mock.TestingT
	Cleanup(func())
}

// NewObjectStore creates a new instance of ObjectStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewObjectStore(t mockConstructorTestingTNewObjectStore) *ObjectStore {
	mock := &ObjectStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
